# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [8]:
import numpy as np

array = np.array([[1, 2], [3, 4]])
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(bordered_array)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [2]:
import numpy as np

print(0 * np.nan)          # nan
print(np.nan == np.nan)   # False
print(np.inf > np.nan)     # False
print(np.nan - np.nan)     # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)      # False


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [9]:
matrix = np.zeros((5, 5))
indices = np.diag_indices(4)
matrix[indices[0] + 1, indices[1]] = [1, 2, 3, 4]
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [10]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
index = np.unravel_index(100, (6, 7, 8))
print(index)  # Output will be (1, 5, 4)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [12]:
checkerboard_tile = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(checkerboard_tile)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [13]:
random_matrix = np.random.rand(5, 5)
normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))
print(normalized_matrix)


[[0.30756954 0.48361903 0.05284579 0.07768388 0.10467272]
 [0.         0.22979095 0.62732332 0.70648149 0.7342594 ]
 [0.50800558 0.7384185  0.72340745 1.         0.19780767]
 [0.28134064 0.14108789 0.37532734 0.72383366 0.97043357]
 [0.24785384 0.29247699 0.38254649 0.36435904 0.63694913]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color_dtype = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])
print(color_dtype)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [15]:
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)
product = np.dot(A, B)
print(product)

[[0.42182074 0.61815136]
 [0.34741485 0.48520465]
 [0.51276009 0.74304115]
 [0.29509929 0.35045835]
 [0.66065839 0.99917164]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)


[ 1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
# Author: Jake VanderPlas

print(sum(range(5), -1))  # Output: 9
from numpy import *
print(sum(range(5), -1))  # Output: 9

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [18]:
Z = np.array([1, 2, 3])

print(Z**Z)      # Legal
print(2 << Z)    # Legal
# print(Z <- Z)  # Illegal syntax
print(1j * Z)    # Legal
print(Z / 1 / 1) # Legal
# print(Z < Z > Z) # Illegal syntax

[ 1  4 27]
[ 4  8 16]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [19]:
print(np.array(0) / np.array(0))          # nan
print(np.array(0) // np.array(0))         # 0
print(np.array([np.nan]).astype(int).astype(float))  # array([nan])

nan
0
[-9.22337204e+18]


/tmp/ipykernel_59925/4151881427.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))          # nan
/tmp/ipykernel_59925/4151881427.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))         # 0
/tmp/ipykernel_59925/4151881427.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))  # array([nan])


#### 29. How to round away from zero a float array ? (★☆☆)

In [20]:
float_array = np.array([-1.5, 1.5, -2.5, 2.5])
rounded_array = np.sign(float_array) * np.ceil(np.abs(float_array))
print(rounded_array)

[-2.  2. -3.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [21]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])
common_values = np.intersect1d(array1, array2)
print(common_values)

[4 5]
