# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__ 

'1.26.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
null_vector.nbytes

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [41]:
np?

Type:        module
String form: <module 'numpy' from '/home/davidkibet/miniconda3/lib/python3.12/site-packages/numpy/__init__.py'>
File:        ~/miniconda3/lib/python3.12/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
null_vector2 = np.zeros(10, dtype=int)
null_vector2[4] = 1
null_vector2

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
vector1 = np.arange(10, 50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [22]:

vector1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [24]:
matrix1 = np.arange(9).reshape(3,3)
matrix1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [26]:

array1 = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(array1)
print(indices)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [28]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [33]:
array_3d = np.random.random((3,3,3))
print(array_3d)

[[[0.51650021 0.35290779 0.78080667]
  [0.37946226 0.00957443 0.15205616]
  [0.75819767 0.19888839 0.42563882]]

 [[0.86079016 0.40994573 0.76108094]
  [0.39058949 0.08531828 0.1160219 ]
  [0.39785707 0.57031369 0.42526491]]

 [[0.30691451 0.86242632 0.44975407]
  [0.56653566 0.90631023 0.48483796]
  [0.46213436 0.56944504 0.87185275]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [36]:
array2 = np.random.random((10,10))
print(array2.min())
print(array2.max())

0.03891114172205279
0.9928333833705406


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [38]:
random_array = np.random.random(30)
print(random_array.mean())

0.43425581901031574


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [40]:
array_2d = np.ones((5,5))
array_2d[1:-1,1:-1] = 0
print(array_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
