# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 61. Find the nearest value from a given value in an array (★★☆)

In [1]:
import numpy as np
def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

# Example usage
arr = np.array([1, 3, 5, 7, 9])
value = 6
nearest_value = find_nearest(arr, value)
print(nearest_value)  # Output: 5


5


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [5]:
A = np.array([[1, 2, 3]])
B = np.array([[4], [5], [6]])

# Using np.nditer to iterate and compute the sum
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y

result = it.operands[2]
print(result)  

[[5 6 7]
 [6 7 8]
 [7 8 9]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj
    def __repr__(self):
        return f"NamedArray(name={self.name}, data={super().__repr__()})"


arr = NamedArray(np.array([1, 2, 3]), name="MyArray")
print(arr)  # Output: NamedArray(name=MyArray, data=[1 2 3])


[1 2 3]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [13]:
def add_to_indices(vector, indices):
    np.add.at(vector, indices,  1)
    return vector

# Example usage
vec = np.array([0, 0, 0, 0, 0])
indices = np.array([1, 1, 1, 1])
result = add_to_indices(vec, indices)
print(result)

[0 4 0 0 0]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [14]:
def accumulate_elements(X, I, F):
    np.add.at(F, I, X)
    return F

# Example usage
X = np.array([1, 2, 3, 4])
I = np.array([0, 1, 0, 2])
F = np.zeros(3)
result = accumulate_elements(X, I, F)
print(result)  # Output: [4. 2. 3.]


[4. 2. 4.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [15]:
def unique_colors(image):
    # Reshape the image to a 2D array of pixels
    pixels = image.reshape(-1, image.shape[2])
    unique_colors = np.unique(pixels, axis=0)
    return unique_colors.shape[0]

# Example usage
image = np.random.randint(0, 256, (100, 100, 3), dtype=np.uint8)
num_colors = unique_colors(image)
print(num_colors)  # Output: (depends on the random image)


9997


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [16]:
def sum_last_two_axes(array):
    return np.sum(array, axis=(-2, -1))

# Example usage
array = np.random.rand(4, 3, 2, 5)
result = sum_last_two_axes(array)
print(result.shape)  # Output: (4, 3)


(4, 3)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [29]:
def compute_means(D, S):
    unique_indices = np.unique(S)
    means = np.array([D[S == idx].mean() for idx in unique_indices])
    return means

# Example usage
D = np.array([1, 2, 3, 4, 5, 6])
S = np.array([0, 0, 1, 1, 2, 2])
result = compute_means(D, S)
print(result)  # Output: [1.5 3.5 5.5]


[1.5 3.5 5.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [28]:
def diagonal_dot(A, B):
    return np.einsum('ij,ji->i', A, B)

# Example usage
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = diagonal_dot(A, B)
print(result)  # Output: [19 43]


[19 50]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [6]:
vector = np.array([1, 2, 3, 4, 5])


new_length = len(vector) + (len(vector) - 1) * 3 
result = np.zeros(new_length, dtype=vector.dtype)

result[::4] = vector  

print(result)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [73]:
def multiply_arrays(A, B):
    return A * B[:, :, np.newaxis]

# Example usage
A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5)
result = multiply_arrays(A, B)
print(result.shape)  # Output: (5, 5, 3)


(5, 5, 3)


#### 72. How to swap two rows of an array? (★★★)

In [72]:
def swap_rows(array, row1, row2):
    array[[row1, row2]] = array[[row2, row1]]
    return array

# Example usage
arr = np.array([[1, 2], [3, 4], [5, 6]])
result = swap_rows(arr, 0, 2)
print(result) 

[[5 6]
 [3 4]
 [1 2]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [71]:
def unique_segments(triplets):
    segments = np.array([[triplets[:, 0], triplets[:, 1]],
                         [triplets[:, 1], triplets[:, 2]],
                         [triplets[:, 2], triplets[:, 0]]]).reshape(-1, 2)
    unique_segments = np.unique(np.sort(segments, axis=1), axis=0)
    return unique_segments

# Example usage
triplets = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4], [0, 2, 4]])
result = unique_segments(triplets)
print(result)

[[0 1]
 [0 2]
 [1 2]
 [2 3]
 [4 4]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [70]:
def bincount_to_array(C):
    return np.repeat(np.arange(len(C)), C)

# Example usage
C = np.array([0, 2, 3, 1])
result = bincount_to_array(C)
print(result)  # Output: [1 1 2 2 2 3]


[1 1 2 2 2 3]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [69]:
def sliding_window_average(arr, window_size):
    return np.convolve(arr, np.ones(window_size)/window_size, mode='valid')

# Example usage
arr = np.array([1, 2, 3, 4, 5])
result = sliding_window_average(arr, 3)
print(result)  # Output: [2. 3. 4.]

[2. 3. 4.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [67]:
def build_shifted_array(Z):
    return np.array([Z[i:i+3] for i in range(len(Z)-2)])

# Example usage
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
result = build_shifted_array(Z)
print(result)


[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [65]:
def negate_in_place(arr):
    arr[:] = ~arr
    return arr

# Example usage
bool_arr = np.array([True, False, True])
result = negate_in_place(bool_arr)
print(result)  # Output: [False  True False]


[False  True False]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [64]:
def distance_to_lines(P0, P1, p):
    return np.abs((P1[:, 1] - P0[:, 1]) * p[0] - (P1[:, 0] - P0[:, 0]) * p[1] + P1[:, 0] * P0[:, 1] - P1[:, 1] * P0[:, 0]) / np.sqrt((P1[:, 1] - P0[:, 1])**2 + (P1[:, 0] - P0[:, 0])**2)

# Example usage
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])
p = np.array([1, 1])
result = distance_to_lines(P0, P1, p)
print(result)  # Output: [1. 0. 1.]


[1. 0. 1.]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [63]:
def distance_to_lines_from_points(P0, P1, P):
    distances = np.zeros((P.shape[0], P0.shape[0]))
    for i in range(P0.shape[0]):
        distances[:, i] = np.abs((P1[i, 1] - P0[i, 1]) * P[:, 0] - (P1[i, 0] - P0[i, 0]) * P[:, 1] + P1[i, 0] * P0[i, 1] - P1[i, 1] * P0[i, 0]) / np.sqrt((P1[i, 1] - P0[i, 1])**2 + (P1[i, 0] - P0[i, 0])**2)
    return distances

# Example usage
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])
P = np.array([[1, 1], [2, 2], [3, 3]])
result = distance_to_lines_from_points(P0, P1, P)
print(result)  # Output: distances from each point to each line


[[1. 0. 1.]
 [2. 1. 0.]
 [3. 2. 1.]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [62]:
import numpy as np

def extract_subpart(array, center, shape, fill_value=0):
    # Calculate slices for the original array
    slices = tuple(
        slice(max(c - s // 2, 0), min(c + (s + 1) // 2, dim))
        for c, s, dim in zip(center, shape, array.shape)
    )
    
    # Create the result subpart with the specified shape and fill value
    subpart = np.full(shape, fill_value)
    
    # Calculate where to place the data in the subpart
    subpart_slices = tuple(
        slice(max(s // 2 - c, 0), max(s // 2 - c, 0) + slices[i].stop - slices[i].start)
        for i, (c, s, dim) in enumerate(zip(center, shape, array.shape))
    )
    
    # Place the extracted array data into the subpart
    subpart[subpart_slices] = array[slices]
    return subpart

# Example usage
array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])
center = (2, 2)
shape = (3, 3)
result = extract_subpart(array, center, shape)
print(result)  # Expected output:
               # [[ 7  8  9]
               #  [12 13 14]
               #  [17 18 19]]


[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [58]:
def generate_sliding_window(Z, window_size):
    return np.array([Z[i:i + window_size] for i in range(len(Z) - window_size + 1)])

# Example usage
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
result = generate_sliding_window(Z, 4)
print(result)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [57]:
def compute_rank(matrix):
    return np.linalg.matrix_rank(matrix)

# Example usage
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = compute_rank(matrix)
print(result)  # Output: 2


2


#### 83. How to find the most frequent value in an array?

In [56]:
from scipy import stats

def most_frequent_value(array):
    return stats.mode(array).mode

# Example usage
array23 = np.array([1, 2, 2, 3, 3, 3, 4])
result = most_frequent_value(array23)
print(result)  # Output: 3


3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [52]:
def extract_3x3_blocks(matrix):
    blocks = np.lib.stride_tricks.as_strided(matrix, shape=(8, 8, 3, 3), strides=matrix.strides + matrix.strides)
    return blocks.reshape(-1, 3, 3)

# Example usage
matrix = np.random.rand(10, 10)
blocks = extract_3x3_blocks(matrix)
print(blocks.shape)  # Output: (64, 3, 3)


(64, 3, 3)


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [51]:
def sum_matrix_products(matrices, vectors):
    return sum(np.dot(matrices[i], vectors[i]) for i in range(len(matrices)))

# Example usage
matrices = [np.random.rand(3, 3) for _ in range(5)]
vectors = [np.random.rand(3, 1) for _ in range(5)]
result = sum_matrix_products(matrices, vectors)
print(result.shape)  # Output: (3, 1)


(3, 1)


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [50]:
def sum_matrix_products(matrices, vectors):
    return sum(np.dot(matrices[i], vectors[i]) for i in range(len(matrices)))

# Example usage
matrices = [np.random.rand(3, 3) for _ in range(5)]
vectors = [np.random.rand(3, 1) for _ in range(5)]
result = sum_matrix_products(matrices, vectors)
print(result.shape)


(3, 1)


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [48]:
def block_sum(array, block_size):
    return array.reshape(array.shape[0] // block_size, block_size, array.shape[1] // block_size, block_size).sum(axis=(1, 3))

# Example usage
array = np.random.rand(16, 16)
result = block_sum(array, 4)
print(result.shape)


(4, 4)


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [46]:
def game_of_life(board, steps):
    for _ in range(steps):
        neighbors = sum(np.roll(np.roll(board, i, 0), j, 1) for i in (-1, 0, 1) for j in (-1, 0, 1) if (i, j) != (0, 0))
        board = (neighbors == 3) | (board & (neighbors == 2))
    return board

# Example usage
board = np.random.randint(2, size=(5, 5))
result = game_of_life(board, 1)
print(result)


[[0 0 1 1 0]
 [0 0 0 1 1]
 [1 1 1 0 1]
 [1 1 0 0 1]
 [1 0 0 0 1]]


#### 89. How to get the n largest values of an array (★★★)

In [45]:
def n_largest_values(array, n):
    return np.partition(array, -n)[-n:]

# Example usage
array = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8])
result = n_largest_values(array, 3)
print(result)

[7 8 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
from itertools import product

def cartesian_product(*arrays):
    return np.array(list(product(*arrays)))

# Example usage
arrays = [np.array([1, 2]), np.array(['a', 'b'])]
result = cartesian_product(*arrays)
print(result) 

[['1' 'a']
 ['1' 'b']
 ['2' 'a']
 ['2' 'b']]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
def create_record_array(array, dtype):
    return np.array(array, dtype=dtype)

# Example usage
array = np.array([(1, 'Alice'), (2, 'Bob')])
dtype = [('id', 'object'), ('name', 'U10')]
result = create_record_array(array, dtype)
print(result)

[[('1', '1') ('Alice', 'Alice')]
 [('2', '2') ('Bob', 'Bob')]]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
def compute_power(Z):
    return Z ** 3, np.power(Z, 3), np.array(list(map(lambda x: x ** 3, Z)))

# Example usage
Z = np.array([1, 2, 3, 4, 5])
result = compute_power(Z)
print(result)  

(array([  1,   8,  27,  64, 125]), array([  1,   8,  27,  64, 125]), array([  1,   8,  27,  64, 125]))


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [38]:
def find_rows_containing_elements(A, B):
    return np.array([row for row in A if all(elem in row for elem in B.flatten())])

# Example usage
A = np.array([[1, 2, 3], [4, 5, 6], [1, 5, 2], [7, 8, 9]])
B = np.array([[1, 2], [5, 6]])
result = find_rows_containing_elements(A, B)
print(result)


[]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [37]:
def extract_unequal_rows(matrix):
    return matrix[np.any(matrix != matrix[:, [0]], axis=1)]

# Example usage
matrix = np.array([[1, 2, 3], [2, 2, 2], [3, 3, 3], [4, 5, 4]])
result = extract_unequal_rows(matrix)
print(result)


[[1 2 3]
 [4 5 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [36]:
def int_to_binary_matrix(vector):
    return np.array([[int(bit) for bit in np.binary_repr(num, width=8)] for num in vector])

# Example usage
vector = np.array([1, 2, 3])
result = int_to_binary_matrix(vector)
print(result) 

[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [34]:
def unique_rows(array):
    return np.unique(array, axis=0)

# Example usage
array = np.array([[1, 2], [2, 3], [1, 2], [4, 5]])
result = unique_rows(array)
print(result)  

[[1 2]
 [2 3]
 [4 5]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [33]:
def sample_path(X, Y, num_samples):
    t = np.linspace(0, 1, num_samples)
    return np.array([np.interp(t, np.linspace(0, 1, len(X)), X),
                     np.interp(t, np.linspace(0, 1, len(Y)), Y)])

# Example usage
X = np.array([0, 1, 2, 3])
Y = np.array([0, 1, 0, -1])
result = sample_path(X, Y, 5)
print(result)  # Output: [[0. 0.5 1. 1.5 2.]
                #          [0. 0.5 1. 0.5 -0.]]


[[ 0.    0.75  1.5   2.25  3.  ]
 [ 0.    0.75  0.5  -0.25 -1.  ]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [32]:
def sample_path(X, Y, num_samples):
    t = np.linspace(0, 1, num_samples)
    return np.array([np.interp(t, np.linspace(0, 1, len(X)), X),
                     np.interp(t, np.linspace(0, 1, len(Y)), Y)])

# Example usage
X = np.array([0, 1, 2, 3])
Y = np.array([0, 1, 0, -1])
result = sample_path(X, Y, 5)
print(result)  # Output: [[0. 0.5 1. 1.5 2.]
                #          [0. 0.5 1. 0.5 -0.]]


[[ 0.    0.75  1.5   2.25  3.  ]
 [ 0.    0.75  0.5  -0.25 -1.  ]]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [31]:
def select_multinomial_rows(X, n):
    return X[np.all(X >= 0, axis=1) & (X.sum(axis=1) == n)]

# Example usage
X = np.array([[1, 2, 3], [2, 2, 2], [3, 3, 3], [0, 0, 0]])
n = 6
result = select_multinomial_rows(X, n)
print(result)  # Output: [[1 2 3]]


[[1 2 3]
 [2 2 2]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [30]:
def bootstrap_confidence_interval(X, n_iterations=1000, confidence_level=0.95):
    means = []
    n = len(X)
    for _ in range(n_iterations):
        sample = np.random.choice(X, size=n, replace=True)
        means.append(np.mean(sample))
    lower_bound = np.percentile(means, (1 - confidence_level) / 2 * 100)
    upper_bound = np.percentile(means, (1 + confidence_level) / 2 * 100)
    return lower_bound, upper_bound

# Example usage
X = np.random.rand(100)
result = bootstrap_confidence_interval(X)
print(result)  # Output: (lower_bound, upper_bound)


(0.43103587225612733, 0.5390153686907675)
