# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [1]:
import numpy as np
import warnings

warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [2]:
result = np.sqrt(-1) == np.emath.sqrt(-1)
print(result) 
#The expression is False

False


/tmp/ipykernel_70525/2807293582.py:1: RuntimeWarning: invalid value encountered in sqrt
  result = np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [3]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print(yesterday, today, tomorrow)

2025-01-18 2025-01-19 2025-01-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [4]:
july_dates = np.arange(np.datetime64('2016-07-01'), np.datetime64('2016-08-01'))
print(july_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [5]:
import numpy as np

A = np.array([1, 2, 3, 4], dtype=float)  # Change dtype to float
B = np.array([5, 6, 7, 8])  # Your array here
np.add(A, B, out=A)  # A = A + B
np.multiply(A, -A / 2, out=A)  # A = A * (-A / 2)

array([-18., -32., -50., -72.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [6]:
arr = np.random.rand(10) * 10  # Random array of positive numbers

# Method 1
int_part1 = np.floor(arr)

# Method 2
int_part2 = np.ceil(arr) - 1

# Method 3
int_part3 = arr.astype(int)

# Method 4
int_part4 = np.trunc(arr)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [7]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [8]:
def generate_integers():
    for i in range(10):
        yield i

array = np.array(list(generate_integers()))
print(array)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [9]:
vector = np.linspace(0, 1, 12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [10]:
random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)
print(sorted_vector)

[0.03614955 0.08293123 0.09756191 0.29706616 0.40587037 0.42662837
 0.6986991  0.76173152 0.78289885 0.80713488]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [11]:
# using python sum
small_array = np.array([2,3,4,5])  # Your small array here
result = sum(small_array)
print(result)


14


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [12]:
A = np.random.rand(10)
B = np.random.rand(10)
are_equal = np.array_equal(A, B)
print(are_equal)


False


#### 43. Make an array immutable (read-only) (★★☆)

In [13]:
array = np.array([...])  # Your array here
array.setflags(write=False)


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [14]:
cartesian = np.random.rand(10, 2)
r = np.sqrt(cartesian[:, 0]**2 + cartesian[:, 1]**2)
theta = np.arctan2(cartesian[:, 1], cartesian[:, 0])
polar = np.column_stack((r, theta))
print(polar)


[[0.38489057 1.22093046]
 [0.57680659 0.1760347 ]
 [1.07953481 0.67290834]
 [0.96184704 0.28339612]
 [1.03814122 0.35421033]
 [0.73251807 1.30242943]
 [1.02203386 0.8752529 ]
 [1.1045349  0.53847645]
 [0.27599769 0.99787989]
 [0.90359885 0.07866578]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [15]:
random_vector = np.random.rand(10)
random_vector[random_vector.argmax()] = 0
print(random_vector)


[0.20257305 0.27413055 0.35622484 0.         0.81529151 0.90990584
 0.85376024 0.67609453 0.09407208 0.1274015 ]
